apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: scn-route
  namespace: scn-httproute-e2e
spec:
  parentRefs:
  - name: scn-gateway
  hostnames:
  - ocibnkctl.local
  rules:
  - matches:
    - path: {type: PathPrefix, value: /}
    backendRefs:
    - name: nginx
      port: 80
