package cluster

import (
	"reflect"
	"testing"
)

func TestParseResolvUpstreams(t *testing.T) {
	tests := []struct {
		name   string
		resolv string
		want   []string
	}{
		{
			name: "docker embedded uses ExtServers comment",
			resolv: "# Generated by Docker Engine.\n" +
				"nameserver 127.0.0.11\n" +
				"search tail27f72.ts.net\n" +
				"options edns0 trust-ad ndots:0\n" +
				"# Based on host file: '/etc/resolv.conf' (internal resolver)\n" +
				"# ExtServers: [185.12.64.1 185.12.64.2]\n",
			want: []string{"185.12.64.1", "185.12.64.2"},
		},
		{
			name:   "real non-loopback nameservers win over ExtServers",
			resolv: "nameserver 192.168.1.1\n# ExtServers: [8.8.8.8]\n",
			want:   []string{"192.168.1.1"},
		},
		{
			name:   "tailscale magicdns nameserver rejected, falls back to ExtServers",
			resolv: "nameserver 100.100.100.100\n# ExtServers: [1.1.1.1 9.9.9.9]\n",
			want:   []string{"1.1.1.1", "9.9.9.9"},
		},
		{
			name:   "ExtServers entries may carry a port",
			resolv: "nameserver 127.0.0.11\n# ExtServers: [185.12.64.1:53 185.12.64.2:53]\n",
			want:   []string{"185.12.64.1", "185.12.64.2"},
		},
		{
			name:   "ipv6 and loopback are skipped, duplicates collapsed",
			resolv: "nameserver ::1\nnameserver 127.0.0.53\nnameserver 8.8.8.8\nnameserver 8.8.8.8\n",
			want:   []string{"8.8.8.8"},
		},
		{
			name:   "nothing usable yields empty",
			resolv: "nameserver 127.0.0.11\nsearch example.com\n",
			want:   nil,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := parseResolvUpstreams(tt.resolv)
			if !reflect.DeepEqual(got, tt.want) {
				t.Fatalf("parseResolvUpstreams() = %v, want %v", got, tt.want)
			}
		})
	}
}
