package cluster

import (
	"fmt"
	"strings"
)

// registryUpstreams is the fixed set of registries tmmlitectl pulls images
// from, in the port order the companion `regcachectl` tool publishes its
// pull-through caches (docker.io:portBase, ghcr.io:portBase+1, …). The
// cross-tool contract is this k3s registries.yaml format, NOT a shared Go
// dependency — keep this table in sync with regcachectl's Upstreams.
var registryUpstreams = []struct{ Host, Remote string }{
	{"docker.io", "https://registry-1.docker.io"},
	{"ghcr.io", "https://ghcr.io"},
	{"quay.io", "https://quay.io"},
	{"repo.f5.com", "https://repo.f5.com"},
}

// RenderRegistriesYAML builds a k3s /etc/rancher/k3s/registries.yaml that
// points each upstream at its host-published pull-through cache
// (http://host:portBase+i), with the real upstream listed second as a
// fallback so a stopped cache degrades to direct pulls instead of breaking
// pulls. host is the address the node containers use to reach the host
// (host.docker.internal, resolved via --add-host host-gateway — see
// K3s.mirrorArgs).
//
// f5User/f5Pass, when non-empty, are the repo.f5.com credentials. They are
// emitted in a `configs` block keyed by the F5 cache's mirror host:port — NOT
// in the cache itself — so the CLUSTER authenticates the credential-free F5
// blob cache, and different clusters/BNK versions can carry different keys
// against the same shared cache.
func RenderRegistriesYAML(host string, portBase int, f5User, f5Pass string) string {
	var b strings.Builder
	b.WriteString("# generated by tmmlitectl — pull-through cache mirrors (regcachectl fleet)\n")
	b.WriteString("mirrors:\n")
	f5Endpoint := ""
	for i, u := range registryUpstreams {
		endpoint := fmt.Sprintf("http://%s:%d", host, portBase+i)
		if u.Host == "repo.f5.com" {
			f5Endpoint = fmt.Sprintf("%s:%d", host, portBase+i)
		}
		b.WriteString(fmt.Sprintf("  %q:\n", u.Host))
		b.WriteString("    endpoint:\n")
		b.WriteString(fmt.Sprintf("      - %q\n", endpoint))
		b.WriteString(fmt.Sprintf("      - %q\n", u.Remote))
	}
	if f5User != "" && f5Endpoint != "" {
		// The client presents these to the F5 blob cache, which relays them
		// upstream (the token exchange goes client→repo.f5.com directly).
		b.WriteString("configs:\n")
		b.WriteString(fmt.Sprintf("  %q:\n", f5Endpoint))
		b.WriteString("    auth:\n")
		b.WriteString(fmt.Sprintf("      username: %q\n", f5User))
		b.WriteString(fmt.Sprintf("      password: %q\n", f5Pass))
	}
	return b.String()
}
