apiVersion: k8s.f5net.com/v1
kind: F5BnkGateway
metadata:
  name: ocibnkctl-udp-lb
  namespace: scn-udp-lb
spec:
  ingressConfig:
    defaultListenerNetworks:
    - name: external
      ipv4BaseCidr: 203.0.113.0/24
      startAddress: 203.0.113.107
      endAddress: 203.0.113.200
      provider: f5-ip-provider
